name: Python test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: acitonsの立ち上げ
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: 必要パッケージのインストール
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
      - name: コードの校正
        run: |
          flake8 . --count --show-source --statistics --exclude=./test_*.py
      - name: テストコード一覧の表示
        run: |
          ls ./test_*.py
      - name: テストコードの実行
        run: |
          pytest test_*.py
      - name: テスト結果の出力
        run: |
          pytest test_fizzbuzz.py --junitxml='test.xml'